export const questions = [
    "Held hands romantically?",
    "Been on a date?",
    "Been in a relationship?",
    "Danced without leaving room for Jesus?",
    "Kissed a non-family member?",
    "Kissed a non-family member on the lips?",
    "French kissed?",
    "French kissed in public?",
    "Kissed on the neck?",
    "Kissed horizontally?",
    "Given or received a hickey?",
    "Kissed or been kissed on the breast?",
    "Kissed someone below the belt?",
    "Kissed for more than two hours consecutively?",
    "Played a game involving stripping?",
    "Seen or been seen by another person in a sensual context?",
    "Masturbated?",
    "Masturbated to a picture or video?",
    "Masturbated while someone else was in the room?",
    "Been caught masturbating?",
    "Masturbated with an inanimate object?",
    "Seen or read pornographic material?",
    "Massaged or been massaged sensually?",
    "Gone through the motions of intercourse while fully dressed?",
    "Undressed or been undressed by a MPS?",
    "Showered with a MPS?",
    "Fondled or had your butt cheeks fondled?",
    "Fondled or had your breasts fondled?",
    "Fondled or had your genitals fondled?",
    "Had or given \"blue balls\"?",
    "Had an orgasm due to someone else's manipulation?",
    "Sent a sexually explicit text or instant message?",
    "Sent or received sexually explicit photographs?",
    "Engaged in sexually explicit activity over video chat?",
    "Cheated on a significant other during a relationship?",
    "Purchased contraceptives?",
    "Gave oral sex?",
    "Received oral sex?",
    "Ingested someone else's genital secretion?",
    "Used a sex toy with a partner?",
    "Spent the night with a MPS?",
    "Been walked in on while engaging in a sexual act?",
    "Kicked a roommate out to commit a sexual act?",
    "Ingested alcohol in a non-religious context?",
    "Played a drinking game?",
    "Been drunk?",
    "Faked sobriety to parents or teachers?",
    "Had severe memory loss due to alcohol?",
    "Used tobacco?",
    "Used marijuana?",
    "Used a drug stronger than marijuana?",
    "Used methamphetamine, crack cocaine, PCP, horse tranquilizers or heroin?",
    "Been sent to the office of a principal, dean or judicial affairs representative for a disciplinary infraction?",
    "Been put on disciplinary probation or suspended?",
    "Urinated in public?",
    "Gone skinny-dipping?",
    "Gone streaking?",
    "Seen a stripper?",
    "Had the police called on you?",
    "Run from the police?",
    "Had the police question you?",
    "Had the police handcuff you?",
    "Been arrested?",
    "Been convicted of a crime?",
    "Been convicted of a felony?",
    "Committed an act of vandalism?",
    "Had sexual intercourse?",
    "?",
    "Had sexual intercourse three or more times in one night?",
    "Had sexual intercourse 10 or more times?",
    "Had sexual intercourse in four or more positions?",
    "Had sexual intercourse with a stranger or person you met within 24 hours?",
    "Had sexual intercourse in a motor vehicle?",
    "Had sexual intercourse outdoors?",
    "Had sexual intercourse in public?",
    "Had sexual intercourse in a swimming pool or hot tub?",
    "Had sexual intercourse in a bed not belonging to you or your partner?",
    "Had sexual intercourse while you or your partner's parents were in the same home?",
    "Had sexual intercourse with non-participating third party in the same room?",
    "Joined the mile high club?",
    "Participated in a \"booty call\" with a partner whom you were not in a relationship with?",
    "Traveled 100 or more miles for the primary purpose of sexual intercourse?",
    "Had sexual intercourse with a partner with a 3 or more year age difference?",
    "Had sexual intercourse with a virgin?",
    "Had sexual intercourse without a condom?",
    "Had a STI test due to reasonable suspicion?",
    "Had a STI?",
    "Had a threesome?",
    "Attended an orgy?",
    "Had two or more distinct acts of sexual intercourse with two or more people within 24 hours?",
    "Had sexual intercourse with five or more partners?",
    "Been photographed or filmed during sexual intercourse by yourself or others?",
    "Had period sex?",
    "Had anal sex?",
    "Had a pregnancy scare?",
    "Impregnated someone or been impregnated?",
    "Paid or been paid for a sexual act?",
    "Committed an act of voyeurism?",
    "Committed an act of incest?",
    "Engaged in bestiality?"
];

export const labels = [
    { range: [0, 14], label: "Choo Choo trainwreck" },
    { range: [15, 29], label: "Community Mattress" },
    { range: [30, 43], label: "Neighborhood Bike" },
    { range: [44, 55], label: "team thot" },
    { range: [56, 68], label: "Seasoned Slut" },
    { range: [69], label: "Nicee" },
    { range: [70, 84], label: "Somebody will match your Freak" },
    { range: [85, 95], label: "Beginner Bop" },
    { range: [96, 100], label: "Goody Two-Shoes" }
];


const innocenceTestQuestions = [
    "been on a date 💕",
    "been in a relationship 🥰",
    "kissed a mps (member of the preferred sex) 😘",
    "made out in public 😐",
    "played a game involved stripping 🩲",
    "masturbated 😈",
    "sent or received underwear pics 👙",
    "sent nudes 🚫",
    "received nudes ❌",
    "sexted 📲",
    "facetime sex 🤳",
    "kissed 3 or more people in one night. 👨‍👩‍👦",
    "FwB 👩🏼‍🤝‍👨🏽",
    "been in love 💖",
    "had a dating app 🔥",
    "paid for a premium version of a dating app 💸",
    "long distance relationship 🛫",
    "asked for a stranger’s contact info #️⃣",
    "been asked for your contact info by a stranger 👻",
    "gotten back with/hooked up with an ex ❎",
    "slid into someone’s DMs 📳",
    "watched porn 🟧⬛️",
    "paid for any porn 🤑",
    "watched porn with mps 🍿",
    "talked to 5 or more people at once 5️⃣",
    "posted a thirst trap 😜",
    "said “i love you” 😍",
    "been to a party 🎉",
    "thrown a party 🥳",
    "drank 🥂",
    "been drunk 😵",
    "blacked or yakked 🥴",
    "played a drinking game 🥤",
    "faked sobriety 🤥",
    "flirted with a stranger to get a free drink 🍻",
    "taken alcohol from your parents 🥃",
    "smoked weed 🍃",
    "done edibles 🍪",
    "hit a bong ⚗️",
    "nicotine (vaped) 💨",
    "smoked a cigarette 🚬",
    "cocaine or a drug stronger 💉",
    "had a fake 🆔",
    "had a fake ID confiscated 👮‍♂️",
    "used a fake to buy alcohol/drugs 💰",
    "used a fake to get into a bar/club 🕺",
    "had the police called on you 🚔",
    "gotten in trouble with school or law 🙁",
    "showered with mps 🚿",
    "given/received a hickey 💋",
    "had/given blue balls 🔵",
    "someone else made you orgasm 🤯",
    "cheated/been cheated on/been cheated with 🤮",
    "bought plan b 👼🏼",
    "bought birth control 💊",
    "given head 🧠",
    "received head 👄",
    "used a sex toy 🧸",
    "spent the night with mps 💤",
    "been walked in on while engaging in a sexual act 😳",
    "sexiled a roommate 👋🏼",
    "had sex 🍆",
    "had sex 3 or more times in one night. 🏘",
    "STI/STD test 🦠",
    "had car sex 🚘",
    "had sex in public 📢",
    "used blindfold/handcuffs in bed 🤭",
    "joined the mile high club 🛫",
    "❓",
    "3some 3️⃣",
    "orgy! 🔢",
    "body count > 5 📈",
    "sex tape. 🎥",
    "anal 🍑",
    "period sex 🩸",
    "bought a pregnancy test 📄",
    "been preggo/ gotten someone preggo 🤰",
    "streaked 👀",
    "skinny dipped 🌊",
    "seen a stripper 👅",
    "run from the police 👮",
    "been questioned by/handcuffed by police 🚨",
    "committed vandalism 🎨",
    "driven under the influence 🚙",
    "texted while driving 💬",
    "gotten a tattoo 🖋️",
    "pierced something other than your ears 👃",
    "stolen something 💲",
    "crashed a car 🏎",
    "blocked someone on social media 👎🏽",
    "gotten kicked out of a party 😡",
    "been at a party that got raided 🚒",
    "snuck out 😰",
    "had corona! 😷",
    "had a crush on a teacher 👩‍🏫",
    "stalked someone’s snapchat location 📍",
    "gotten with 2+ people in the same friend group 👏🏼",
    "whole snap best friends list has been love interests 😎",
    "gotten with someone 3+ years older than you 👵",
    "gotten with someone 3+ years younger than you 👶"
  ];